### ISSUE TITLE
Bring in DevOps updates

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar-backend#14]
This repo predates the "official" release of our QuickStart.  Misc ticket to bring over new pipeline features and actions.  Please expect multiple tickets.

**Comment by RMCampos** [comment]
@DerekRoberts great job! Thanks for bringing that in. I believe that our `dev` workflow are working almost as expected (I think it's a little behind the latest version of the deployer-action) but for `test` and `prod` definitely some work is required, since all the workflows are still using the manual deploy actions.
